on:
  workflow_call:
    inputs:
      env:
        required: false
        type: string
      gh_runner:
        required: false
        type: string
    secrets:
      token:
        required: false

jobs:
  test:
    name: Test
    runs-on: [${{ inputs.gh_runner}}]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}