on:
  workflow_call:

jobs:
  tf_base:
    runs-on: [Linux]
    steps:
      - name: Terraform fmt_check
        uses: otc-code/gh-actions/terraform@main
        with:
          TF_DIR: '${{ github.workspace }}'
          TERRAFORM_ACTION: 'fmt_check'
      - name: Terraform init
        uses: ./terraform/
        with:
          TF_DIR: '${{ github.workspace }}'
          TERRAFORM_ACTION: 'init'

      - name: Terraform validate
        uses: otc-code/gh-actions/terraform@main
        with:
          TF_DIR: '${{ github.workspace }}'
          TERRAFORM_ACTION: 'validate'

      - name: Terraform compliance
        uses: otc-code/gh-actions/terraform@main
        with:
          TF_DIR: '${{ github.workspace }}/test/terraform'
          TERRAFORM_ACTION: 'compliance'

      - name: Terraform security
        uses: checkmarx/kics-github-action@v1.6.3
        with:
          path: '${{ github.workspace }}'
          ignore_on_exit: results
          cloud_provider: 'aws, azure, gcp'
          token: ${{ secrets.ORG_GITHUB_TOKEN }}