on:
  workflow_call:

jobs:
  tf_base:
    runs-on: [Linux]
    steps:
      - name: Terraform fmt_check
        uses: otc-code/gh-actions/terraform@main
        with:
          TF_DIR: '${{ github.workspace }}'
          TERRAFORM_ACTION: 'fmt_check' 
